-- M3 adds fh-show-points; M4 adds the layer-override startup strings.
data:extend({
  {
    type = "int-setting",
    name = "fh-points-per-level",
    setting_type = "startup",
    default_value = 5,
    minimum_value = 0,
    order = "b[tech]-a[points-per-level]",
  },
  {
    type = "double-setting",
    name = "fh-tech-cost-multiplier",
    setting_type = "startup",
    default_value = 1,
    minimum_value = 0.1,
    order = "b[tech]-b[cost-multiplier]",
  },
  {
    type = "string-setting",
    name = "fh-tech-tiers",
    setting_type = "startup",
    default_value = "",
    allow_blank = true,
    order = "b[tech]-c[tiers-override]",
  },
  {
    type = "int-setting",
    name = "fh-settlement-charter",
    setting_type = "runtime-global",
    default_value = 30,
    minimum_value = 0,
    order = "a[economy]-c[settlement-charter]",
  },
  {
    type = "bool-setting",
    name = "fh-print-claims",
    setting_type = "runtime-global",
    default_value = true,
    order = "c[ux]-a[print-claims]",
  },
  {
    type = "int-setting",
    name = "fh-starting-points",
    setting_type = "runtime-global",
    default_value = 75,
    minimum_value = 0,
    order = "a[economy]-a[starting-points]",
  },
  {
    type = "int-setting",
    name = "fh-refund-percent",
    setting_type = "runtime-global",
    default_value = 25,
    minimum_value = 0,
    maximum_value = 100,
    order = "a[economy]-b[refund-percent]",
  },
})
